@startuml

abstract class Character {
        void run()
        {abstract} void attack((Slime slime)
}
class  Hero extends Character {
    +String name;
    -int age;

    void attack(Slime slime)

}

class SuperHero extends Hero {
}

class Wizard extends Hero

class Cleric implements Hero {}




@enduml