@startuml

abstract class Zerg implements Regeneratedable, Attackable {

}
abstract class ZergUnit extends Zerg {

    + String name
    + int healthPoint
}
abstract class ZergStructure extends Zerg implements Bionic {
}
'------저그최종유닛
class Zergling extends ZergUnit implements Bionic {
    + void attack()
}

class Hydra extends ZergUnit implements Bionic {
    + void attack()
}


@enduml